apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: books.nigelpoulton.com
spec:
  # Api group
  group: nigelpoulton.com
  # Can be Namespaced or Cluster
  scope:  Cluster
  names:
    plural: books
    singular: book
    kind: Book
    shortNames:
      - bk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bookTitle: 
                  type: string
                topic:
                  type: string
                edition:
                  type: integer
      additionalPrinterColumns:
        - name: Title
          type: string
          description: Title of the book
          jsonPath: .spec.bookTitle
        - name: Edition
          type: integer
          description: Edition number
          jsonPath: .spec.edition
---
apiVersion: nigelpoulton.com/v1
kind: Book
metadata:
  name: tkb
spec:
  bookTitle: "The Kubernetes Book"
  topic: Kubernetes
  edition: 2